### ISSUE TITLE
Illogical results

### ISSUE THREAD

**Issue by meetxinzhang** [Jerkwin/gmxtool#2]
The values of bind free energr of protein-protein system are used to be positive, but change greatly after adjusting df slightly in the code. I have to say that the calculation result of this script is too illogical. And the author seems to have no intention of maintaining.

**Comment by Jerkwin** [comment]
如果你的蛋白带有净电荷, 得到正的结合能很正常. 这和MM静电能的计算方法太粗略有关, 和我的脚本无关. 你要做的是去多看几篇文献, 多看看相关的理论, 测试一下其他MMPBSA代码的结果, 试着理解一下为什么. 而不是单纯地抱怨我的脚本给出的结果不合你意.
至于df对结果的影响, 这是APBS应有之义, 我给的文档中有相关的讨论. 如果你没有读过, 那我建议你先好好读读, 别把APBS当做黑盒子. 如果你觉得APBS的计算有问题, 那么你到APBS那里去提问题.

**Comment by Jerkwin** [comment]
如果你的蛋白带有净电荷, 得到正的结合能很正常. 这和MM静电能的计算方法太粗略有关, 和我的脚本无关. 你要做的是去多看几篇文献, 多看看相关的理论, 测试一下其他MMPBSA代码的结果, 试着理解一下为什么. 而不是单纯地抱怨我的脚本给出的结果不合你意.

至于`df`对结果的影响, 这是APBS应有之义, 我给的文档中有相关的讨论. 如果你没有读过, 那我建议你先好好读读, 别把APBS当做黑盒子. 如果你觉得APBS的计算有问题, 那么你到APBS那里去提问题.

**Comment by meetxinzhang** [comment]
@Jerkwin 
thinks for your reply, and I will follow your advices. My experimental shows that mmgbsa will not be positive.

**Comment by Jerkwin** [comment]
你遇到的问题不是孤例, 目前也没有成熟常规的解决方法. 我很快就会更新一下脚本, 实现一篇文献上的方法, 连带会发布一篇说明, 用于解决带净电荷体系结合能为正的问题. 

另外, 如果你真想练习英文, 请先做到不出现拼写错误和错词: `energr`, `My experimental`.

**Comment by Jerkwin** [comment]
脚本已更新, 请测试, 看是否解决了你的问题. 相关说明见脚本文档.

**Comment by meetxinzhang** [comment]
感谢更新。我用新脚本计算， 无论加不加 -ts ie -cou dh 选项。计算结果都是一样的，并且 apbs 会报出问题（但这个问题不影响后续计算）：

```
>> 3. run MM-PBSA calculatons
   >> Frame   1/3: _pid~0nsasc_getToken: Error occurred (bailing out).
Vio_scanf: Format problem with input.
asc_getToken: Error occurred (bailing out).
Vio_scanf: Format problem with input.
asc_getToken: Error occurred (bailing out).
Vio_scanf: Format problem with input.
VIOsigHand: yow! caught a hot SIGPIPE....diffused it.
asc_getToken: Error occurred (bailing out).
Vio_scanf: Format problem with input.
VIOsigHand: yow! caught a hot SIGPIPE....diffused it.
    MM-PBSA(with DH) =  -1377.458( -787.995) kJ/mol
   >> Frame   2/3: _pid~1nsVIOsigHand: yow! caught a hot SIGPIPE....diffused it.
VIOsigHand: yow! caught a hot SIGPIPE....diffused it.
VIOsigHand: yow! caught a hot SIGPIPE....diffused it.
VIOsigHand: yow! caught a hot SIGPIPE....diffused it.
VIOsigHand: yow! caught a hot SIGPIPE....diffused it.
VIOsigHand: yow! caught a hot SIGPIPE....diffused it
```

**Comment by Jerkwin** [comment]
我默认打开了那两个选项, 因为没有必要算两次. 你要关闭它们, 可以将脚本中的`useDH`和`useTS`初始化为`0`.

至于你遇到的多余输出, 是APBS的输出, 脚本log中有一句说明

   2019-11-06: apbs FILE.apbs &> FILE.out
               on ubuntu 18.04 may not work, then delete &

我没有Linux机器做测试, 无法给出更好的解决方法. 你要是有, 欢迎指出.

**Comment by meetxinzhang** [comment]
@Jerkwin Hi
我正是要打开 dh 和 ie ，我也看了你说的那篇中国物理学报的论文，我按照他的论文protocol重做了ACE2和Spike RBD的实验(pdb id: 6vw1)，但没有复现出他的结果 (-13.3 kcal/mol)，问题应该出在PB SA计算上，如下所示，这两项为0:
```
   #Frame      Binding( with DH ) |    MM    ( with DH )    PB        SA     |   COU    ( with DH )     VDW   |       PBcom        PBpro        PBlig  |    SAcom     SApro     SAlig
_pid~0ns     -1386.615( -809.194) | -1386.615( -809.194)     0.000     0.000 |  -998.838( -421.417)  -387.777 |        0.000        0.000        0.000 |     0.000     0.000     0.000
_pid~1ns     -1455.810( -763.502) | -1455.810( -763.502)     0.000     0.000 | -1079.561( -387.253)  -376.249 |        0.000        0.000        0.000 |     0.000     0.000     0.000
_pid~2ns     -1360.879( -689.528) | -1360.879( -689.528)     0.000     0.000 |  -959.862( -288.511)  -401.017 |        0.000        0.000        0.000 |     0.000     0.000     0.000
----------------------------------|------------------------------------------|--------------------------------|
mean         -1401.101( -754.075) | -1401.101( -754.075)     0.000     0.000 | -1012.754( -365.727)  -388.348 |
-TdS            37.499(   61.823) |
----------------------------------|
  dG         -1363.602( -692.252) kJ/mol =  -325.909( -165.452) kcal/mol
```
我正在检查源代码

**Comment by meetxinzhang** [comment]
经过我的测试（linux ubuntu 20.04），在源代码 598 行：
`cmd=apbs" "Fout".apbs & > "Fout".out 2>& 1";`
去掉 & 就可以去掉多余的 APBS 输出

并且 PB SA 项也有了非0结果，总的绝对结合能开始趋于合理：
```
   #Frame      Binding( with DH ) |    MM    ( with DH )    PB        SA     |   COU    ( with DH )     VDW   |       PBcom        PBpro        PBlig  |    SAcom     SApro     SAlig
_pid~0ns      -698.455( -121.035) | -1386.615( -809.194)   739.687   -51.527 |  -998.838( -421.417)  -387.777 |   -21789.332   -16861.002    -5668.016 |   779.168   586.656   244.040
_pid~1ns      -842.923( -150.615) | -1455.810( -763.502)   662.262   -49.375 | -1079.561( -387.253)  -376.249 |   -22983.154   -17712.573    -5932.843 |   804.836   602.177   252.034
_pid~2ns      -860.986( -189.636) | -1360.879( -689.528)   548.785   -48.892 |  -959.862( -288.511)  -401.017 |   -23287.636   -17806.073    -6030.348 |   817.803   613.504   253.191
----------------------------------|------------------------------------------|--------------------------------|
mean          -800.788( -153.762) | -1401.101( -754.075)   650.245   -49.932 | -1012.754( -365.727)  -388.348 |
-TdS            37.499(   61.823) |
----------------------------------|
  dG          -763.289(  -91.939) kJ/mol =  -182.431(  -21.974) kcal/mol
```
我初步猜测是因为代码599行：
`cmd | getline err; close(cmd)`
捕获了上面说到的 APBS 输出的问题，然后就结束了程序，所以 PB SA 项没有计算完成。

 -21.974 kcal/mol 接近合理，但距离论文里的结果还是有 10 的差距，我现在调整下 df 之类的参数

另外我之前发现，如果在index.ndx中定义的group有重叠，在代码553行
`Ecou   = qi*Qatm[jj]/r;`
由于同一个原子，所以距离为0，会报除数为0的错误
建议加一个 if 获这个bug:
```
f(r==0){
	echo  "you should check whether groups in .ndx file overlps atoms."
        exit 1
}
```

**Comment by Jerkwin** [comment]
谢谢说明.

改为 `cmd=apbs" "Fout".apbs > "Fout".out 2>& 1";` 是不是就可以了?

差距10的问题, 可能和你算的帧数过少, 设置不同有关. 此外, 新脚本默认使用了`npbe`, 你可以试试改为`lpbe`看结果如何.

**Comment by meetxinzhang** [comment]
@Jerkwin 
改为 `cmd=apbs" "Fout".apbs > "Fout".out 2> 1";`
我算了很多帧，某些帧的结果很好。

我删掉了前面的 `trjconv="$gmx trjconv -dt 1000" `， 在预处理轨迹那一步手动定义时间（帧）范围：
` $trjconv  -s $tpr -n $ndx -f $trj -o $trjwho.xtc -b 1000 -e 2000 -skip 10 &> $scr -pbc whole`
请问这样是否同时影响到 interaction entropy 的计算样本？

**Comment by Jerkwin** [comment]
你不能说某些帧结果很好, 这没有意义. 因为体系本来就是有波动的, 不同帧结果差距很大也是正常的. 减少结果波动的方法是增大轨迹的长度, 而且要使用间隔尽可能大的帧. 想想RMSD.

你给的那条命令只算了1 ns, 这意义不大, 因为在1 ns时间尺度内, 蛋白体系不可能有大变化, 坐标相关性很大, 波动当然小. 你能用1 ns的RMSD说明体系平衡好了么?

**Comment by meetxinzhang** [comment]
@Jerkwin 
“使用间隔尽可能大的帧”，这句话没怎么明白，是指的是采样间隔吗？所以之前使用了` -dt 1000`，是这样理解吗？可这样是为什么，增加 构象 的可探索空间吗？请指正。
我老师让我先计算所有轨迹的平均结构，然后选择相对平均结构 RMSD 最小的某一帧或几帧来计算，这个方法和您所说“不能说某些帧结果很好, 这没有意义. 因为体系本来就是有波动的, 不同帧结果差距很大也是正常的. 减少结果波动的方法是增大轨迹的长度”是相违背的吗？

**Comment by Jerkwin** [comment]
我下面说了, 间隔小的构型直接相关性大, 也可以理解成增加构象空间的大小.

我不公开评价你老师的观点.

**Comment by liuyujie714** [comment]
> 谢谢说明.
> 
> 改为 `cmd=apbs" "Fout".apbs > "Fout".out 2>& 1";` 是不是就可以了?
> 
> 差距10的问题, 可能和你算的帧数过少, 设置不同有关. 此外, 新脚本默认使用了`npbe`, 你可以试试改为`lpbe`看结果如何.

李老师，下次更新这个脚本时，可以就去掉那个&和log关于Ubuntu系统的那行了。好像是因为Ubuntu默认的shell是dash，这个导致&>的写法有问题。
```
cmd=apbs" "Fout".apbs > "Fout".out 2>&1"
```
这个在各大Linux平台通用。

**Comment by Jerkwin** [comment]
明白了. 

参考:
- [Ubuntu切换默认sh为bash或者dash](https://blog.csdn.net/gatieme/article/details/52136411)
- [Dash与Bash的语法区别](https://www.2cto.com/os/201305/210033.html)
- [How do you change the default shell for ALL USERS to bash?](https://askubuntu.com/questions/28969/how-do-you-change-the-default-shell-for-all-users-to-bash)

**Comment by liuyujie714** [comment]
> 明白了.
> 
> 参考:
> 
> * [Ubuntu切换默认sh为bash或者dash](https://blog.csdn.net/gatieme/article/details/52136411)
> * [Dash与Bash的语法区别](https://www.2cto.com/os/201305/210033.html)
> * [How do you change the default shell for ALL USERS to bash?](https://askubuntu.com/questions/28969/how-do-you-change-the-default-shell-for-all-users-to-bash)

还有个管道的问题不知道您测试时候遇到过没有。就是每一帧算完以后，MMPBSA.dat文件没有内容是空的(可能还有其他文件，我没关注)，只有全部计算完以后才有内容。我测试的时候非得加上fflush才会正常。
https://github.com/liuyujie714/gmxtool/commit/1f4c1b1c2568568140b6fce8ea58f9ae59c8906d

**Comment by Jerkwin** [comment]
好, 我把你的代码合并进去了. 但没有验证非gawk是否支持`systime`和`fflush`.

**Comment by aptamer1234** [comment]
李老师您好，我用gmx_mmpbsa在windows上模拟遇到几个问题想请教您一下，请问_pid~MMPBSA结果中的Binding( with DH )这个括号内的DH表示什么？最后的△G值是应该看括号内的还是括号外的？
我模拟了10ns的时间，RMSD已经平了，可是模拟得到的△G（使用的是括号外面的）使用公式∆G=RTlnKd换算得到的解离常数Kd与实际相差很大，模拟得到的Kd为10^-60nM，而实际是1nM左右，请问我应该什么参数让结果更准确些？

**Comment by Jerkwin** [comment]
`DH`代表德拜-修克尔修正, 具体的含义看相应文档说明, 以及那里给出的参考文献. 具体用哪个值, 根据你的体系而定, 如果二者相差不大, 就用未修正的; 如果未修正的结果很异常, 就用修正的; 如果二者都异常, 或者你计算有误, 或者体系不适合用PBSA方法.

PBSA方法很粗略, 一般没法直接与实验对比, 换算到Kd, 那差距就更大了, 所以得到很小的Kd比较常见. 至于具体如何算才能更准确, 很难说, 因为影响因素很多. 既有方法自身的局限性, 也有参数的问题, 没法一概而论. 去看看相应的论文吧.

**Comment by aptamer1234** [comment]
> `DH`代表德拜-修克尔修正, 具体的含义看相应文档说明, 以及那里给出的参考文献. 具体用哪个值, 根据你的体系而定, 如果二者相差不大, 就用未修正的; 如果未修正的结果很异常, 就用修正的; 如果二者都异常, 或者你计算有误, 或者体系不适合用PBSA方法.
> 
> PBSA方法很粗略, 一般没法直接与实验对比, 换算到Kd, 那差距就更大了, 所以得到很小的Kd比较常见. 至于具体如何算才能更准确, 很难说, 因为影响因素很多. 既有方法自身的局限性, 也有参数的问题, 没法一概而论. 去看看相应的论文吧.

好的，谢谢您的回复，我再试一下别的方法

**Comment by c00jsw00** [comment]
MMPBSA 得到的DELTA G 很難跟實驗的Kd 做比較...也許發展一個比較好的score function 包含(GB..PB 等等一堆 很像SIE)..比較好

**Comment by Jerkwin** [comment]
发展打分函数一般是对接程序的任务, 这个脚本是专门用来算简单的MMPBSA的, 不涉及对接, 所以不会专门处理打分函数. 但是, 如果有些简单的打分函数实现, 加上也可以.

**Comment by c00jsw00** [comment]
兄臺你好 目前就是MMPBA 基本與理論上無法像QM一樣可以準確預測..個人覺得是時候可以發展一套比較準確的PPI score function ...可以用在CNN OR RNN ...for antibody ...etc..

**Comment by Jerkwin** [comment]
我对前面一句持保留意见, QM的计算值也很难说准确, 因为QMPBSA结果和实验值的相关性并不好于MMPBSA, 大致都在0.6左右, QM的结果取决于所用方法的水平, 高水平的方法很难处理大的体系, 低水平的方法与MM比优势并不大. 至于熵的计算, MM. QM都很难处理或计算困难, 这是本质上的困难, 不是简单的打分函数能解决的.
