### ISSUE TITLE
Make vmd always at the top 

### ISSUE THREAD

**Issue by kexul** [Jerkwin/gmxtool#3]
Hi, thanks for your tool to make vmd automatically resize, is it possible to make it always at the top of the windows? It's annoying to click the 3 windows of vmd when I switched to another program and then switch back.

**Comment by Jerkwin** [comment]
I updated `wvmd.zip` file and you will find a `wvmd_ontop.exe` in it. This exe will set all vmd windows always on top, although I am still not sure this is a good option because you need to switch the ontop status sometimes.

**Comment by kexul** [comment]
> I updated `wvmd.zip` file and you will find a `wvmd_ontop.exe` in it. This exe will set all vmd windows always on top, although I am still not sure this is a good option because you need to switch the ontop status sometimes.

Thank you so much! It worked perfectly!
