### ISSUE TITLE
Awk error

### ISSUE THREAD

**Issue by pallavsen007** [Jerkwin/gmxtool#4]
Hello Dr. Li,
I have been encountering an error with the gmx_mmpbsa script where the script after running for a few frames say 140 or 150, the calculation stops with an error stating something like:
`awk: cmd. line:183: (FILENAME=_pid.pdb FNR=3810933) fatal: attempt to access field -4`
for which i searched through forums and found out that the error means that in the line number 3810933 which happens to be the last line the _pid.pdb (input file) it is trying to get the value of $(NF-4) which is failing as there is no 4th column/field in that particular line of my input file. The last line in my input file is ENDMDL.
PS: I have had all the trjconv functionalities as they were ending up in generating a lot of errors for me, hence I decided to create an index file containing only protein and ligand and thereafter dumped the trajectory with this index file and also dumped the _pid.pdb file with trjconv using the same index file.
Can you please help me figure out where I am getting it wrong ?
Moreover I have another question regarding calculating the MM(COU) part, do we need to input it in command line exclusively as -cou dh to calculate by Debye Huckel Screening or it does calculate it by default?

**Comment by Jerkwin** [comment]
Hi Pallav,

I undertand the error and what you did, my suggestion is that, the tpr, xtc(or trr), ndx must be consistent, which means they all include the same number of atoms. Using a xtc including only protein and ligand with the original tpr and ndx will not work since the index number in the xtc changed. If this is not the problem, I need to check the file to know where the error came from.

For the DH correction, the script will calcu;ate it by default, it's not neccesaary to use `-cou dh` option.

Jicun

**Comment by pallavsen007** [comment]
Thanks a lot for the prompt response. Will try and certainly get back to you.

**Comment by pallavsen007** [comment]
> my suggestion is that, the tpr, xtc(or trr), ndx must be consistent, which means they all include the same number of atoms. Using a xtc including only protein and ligand with the original tpr and ndx will not work since the index number in the xtc changed
Hello Dr. Li,
I tried as you have said with the same number of atoms in xtc, ndx and tpr file, all the values come out to be zero. On the contrary when it is calculated with the original tpr the calculations can be done albeit with small number of frames however the problem arises when i get on to calculate with large number of frames i get the aforementioned error.
However it is to be noted I created the tpr by using gmx convert-tpr and by supplying with the index file. Should I give it a shot using gmx grompp?
 
Below is an output of calculation when the same number of atoms in xtc,tpr and ndx file are considered.

>> 0. set up environmets and parameters: OK !

>> 1. preprocessing trajectory: OK !

>> 2. generate qrv file: OK !

>> 3. run MM-PBSA calculatons
   >> Frame   1/21: _pid~30ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame   2/21: _pid~31ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame   3/21: _pid~32ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame   4/21: _pid~33ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame   5/21: _pid~34ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame   6/21: _pid~35ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame   7/21: _pid~36ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame   8/21: _pid~37ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame   9/21: _pid~38ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame  10/21: _pid~39ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:11s
   >> Frame  11/21: _pid~40ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:10s
   >> Frame  12/21: _pid~41ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:09s
   >> Frame  13/21: _pid~42ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame  14/21: _pid~43ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame  15/21: _pid~44ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame  16/21: _pid~45ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame  17/21: _pid~46ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame  18/21: _pid~47ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame  19/21: _pid~48ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame  20/21: _pid~49ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s
   >> Frame  21/21: _pid~50ns  MM-PBSA(with DH) =     0.000(    0.000) kJ/mol    Estimated Time Remaining: ~ 0h:00m:00s

**Comment by Jerkwin** [comment]
Please try `grompp` first. If the error remains, I would like to check the input files.

**Comment by pallavsen007** [comment]
Dear Dr. Li, the particular problem I'm encountering with the awk error is something strange and haven't been able to figure it out since the script runs perfectly as with smaller number of frames say 10,15, 20 or 100 everything is fine but when the number of frames are increased to 200 or more, I'm particulary encountering the error in the 146th frame which has been atleast 3-4 times which happens to be very strange. Do you suggest in changing something in the script itself?

**Comment by Jerkwin** [comment]
I need to check the files to see why. If it's fine, you can send the input files to `jerkwin@gmail.com`, or send me the sharing link. I feel this error maybe come from the memory issues.

**Comment by Jerkwin** [comment]
I was able to reproduce the problem on Linux and it turned out that I forgot to close some of the opened files in awk. If there are too many opened files, awk will fail. The latest version fixed this bug.

**Comment by pallavsen007** [comment]
Dear Dr. Li, 
The problem with generating a truncated tpr file persists even with newest version of the script with PB and SA values being calculated to zero. Atleast that's what I have found out in Linux. By truncated tpr I mean the tpr having the same number of atoms as the trajectory file and the index file.

**Comment by Jerkwin** [comment]
Please try the latest version, I fixed some issues with APBS.
