### ISSUE TITLE
trr2all: Can't recognize gmx dump with trr2all Tool on Linux Cluster

### ISSUE THREAD

**Issue by unknown-fractal** [Jerkwin/gmxtool#9]
Dear Dr. Li,

I encountered some issues while using your trr2all tool. Due to the significant computational load, I attempted to utilize the tool on a Linux cluster. It seems that I managed to run the .exe file using Wine, yet encountered errors during execution, as follows:

```
Can't recognize 'gmx_mpi dump -s /home/aczzq/ach-test.tpr -quiet ' as an internal or external command, or batch script.
At line 95 of file G:\Dropbox\prog\trr2all\trr2all.f90 (unit = 100, file = '/home/aczzq/ach-test.dmp')
Fortran runtime error: End of file

Error termination. Backtrace:

Could not print backtrace: executable file is not COFF
#0  0xffffffff
#1  0xffffffff
#2  0xffffffff
#3  0xffffffff
#4  0xffffffff
#5  0xffffffff
#6  0xffffffff
#7  0xffffffff
#8  0xffffffff
#9  0xffffffff
#10  0xffffffff
#11  0xffffffff
#12  0xffffffff
#13  0xffffffff
#14  0xffffffff
#15  0xffffffff
#16  0xffffffff
```

Given that your tool is compiled in .exe format, I find it challenging to pinpoint the source of the problem. I attempted to run the problematic command (`gmx_mpi dump -s /home/aczzq/ach-test.tpr -quiet`) in the terminal, and it executed without errors. Hence, I am uncertain about resolving this issue and would greatly appreciate your assistance amidst your busy schedule.

Thank you very much.

**Comment by Jerkwin** [comment]
Hi,

Sorry for the delay reply since I was on vacation last week.

For the issue, I would suggest trying using full path of gmx for `-gmx` option. If it still fails, please let me know through my Gmail and I will send you the source code so that you can compile it on Linux.

Jicun

**Comment by unknown-fractal** [comment]
> Hi,
> 
> Sorry for the delay reply since I was on vacation last week.
> 
> For the issue, I would suggest trying using full path of gmx for `-gmx` option. If it still fails, please let me know through my Gmail and I will send you the source code so that you can compile it on Linux.
> 
> Jicun

Dear Dr. Li,
Thank you very much for your response. It seems that my issue did indeed occur for this reason. Unfortunately, due to the urgency of my work, I had already carried out a similar operation through other means, and therefore was unable to reply promptly. Nevertheless, I appreciate your solution.
